version: '3'
services:
  dev:
    image: avejidah/node-dubnium:latest
    volumes:
      - .:/home/node/dev
    container_name: formn-cli-dev
    ports:
      - "9229:9229"
    stdin_open: true
    tty: true
    environment:
      - SHELL=/bin/bash

